<?php
$ot = $this->object_title;
//$desc = $this->description;
//$mqtt_st = $this->getProperty('mqtt_status');
//$telegram_st = $this->getProperty('telegram_status');
//$registerEvent_st = $this->getProperty('registerEvent_status');
//$write_to_properties = $this->getProperty('write_to_properties');
$pass = $this->getProperty('passw');
$ipterm = 'http://'.$this->getProperty('ip4').':'.$this->getProperty('port');

$getList = getURL($ipterm.'/?cmd=listSettings&password='.urlencode($pass).'&type=json');
//echo $getInfo; // здесь ответ от запроса к Fully в json
//echo '<br>';
$state = json_decode($getList, true);
//---------------------------------------------------------------print_r($array);
$this->setProperty('mdmDisableVolumeButtons', $state['mdmDisableVolumeButtons']); // : false,
//$this->setProperty('', $state['']); //                                             : "200",
$this->setProperty('playMedia', $state['playMedia']); //                             : true,
$this->setProperty('actionBarFgColor', $state['actionBarFgColor']); //               : -1,
$this->setProperty('deleteHistoryOnReload', $state['deleteHistoryOnReload']); //     : true,
$this->setProperty('wifiSSID', $state['wifiSSID']); //                               : "dsys2",
$this->setProperty('actionBarBgUrl', $state['actionBarBgUrl']); //                   : "",
$this->setProperty('mdmApkToInstall', $state['mdmApkToInstall']); //                 : "",
$this->setProperty('mdmDisableADB', $state['mdmDisableADB']); //                     : false,
$this->setProperty('movementWhenUnplugged', $state['movementWhenUnplugged']); //     : false,
$this->setProperty('tabsBgColor', $state['tabsBgColor']); //                         : -2236963,
$this->setProperty('errorUrlOnDisconnection', $state['errorUrlOnDisconnection']); // : "0",
$this->setProperty('screensaverBrightness', $state['screensaverBrightness']); //     : "10",
$this->setProperty('showActionBar', $state['showActionBar']); //                     : false,
$this->setProperty('mdmDisableScreenCapture', $state['mdmDisableScreenCapture']); // : false,
$this->setProperty('restartOnCrash', $state['restartOnCrash']); //                   : true,
$this->setProperty('deleteWebstorageOnReload', $state['deleteWebstorageOnReload']); //: true,
$this->setProperty('kioskMode', $state['kioskMode']); //                             : true,
$this->setProperty('showStatusBar', $state['showStatusBar']); //                     : false,
$this->setProperty('kioskWifiPinAction', $state['kioskWifiPinAction']); //           : "0",
$this->setProperty('mqttBrokerUrl', $state['mqttBrokerUrl']); //                     : "tcp://m2.wqtt.ru:8901",
$this->setProperty('removeNavigationBar', $state['removeNavigationBar']); //         : false,
$this->setProperty('kioskAppWhitelist', $state['kioskAppWhitelist']); //             : " com.thanksmister.iot.mqtt.alarmpanel com.android.chrome com.google.android.apps.nbu.files de.ozerov.fully ru.codedevice.iobrokerpawii ru.smartliving.majordroid in.dc297.mqttclpro",
$this->setProperty('softKeyboard', $state['softKeyboard']); //                       : true,
$this->setProperty('kioskHomeStartURL', $state['kioskHomeStartURL']); //             : true,
$this->setProperty('authPassword', $state['authPassword']); //                       : "",
$this->setProperty('launchOnBoot', $state['launchOnBoot']); //                       : true,
$this->setProperty('knoxDisableUsbHostStorage', $state['knoxDisableUsbHostStorage']); //: false,
$this->setProperty('mdmPasswordQuality', $state['mdmPasswordQuality']); //           : "0",
$this->setProperty('resendFormData', $state['resendFormData']); //                   : true,
$this->setProperty('clearCacheEach', $state['clearCacheEach']); //                   : true,
$this->setProperty('sleepOnPowerConnect', $state['sleepOnPowerConnect']); //         : false,
$this->setProperty('knoxDisableAirViewMode', $state['knoxDisableAirViewMode']); //   : false,
$this->setProperty('pauseMotionInBackground', $state['pauseMotionInBackground']); // : true,
$this->setProperty('mqttBrokerPassword', $state['mqttBrokerPassword']); //           : "xbmc",
$this->setProperty('rootEnable', $state['rootEnable']); //                           : true,
$this->setProperty('resetZoomEach', $state['resetZoomEach']); //                     : true,
$this->setProperty('showHomeButton', $state['showHomeButton']); //                   : true,
$this->setProperty('wifiMode', $state['wifiMode']); //                               : "1",
$this->setProperty('motionCameraId', $state['motionCameraId']); //                   : "",
$this->setProperty('waitInternetOnReload', $state['waitInternetOnReload']); //       : true,
$this->setProperty('inUseWhileAnotherAppInForeground', $state['inUseWhileAnotherAppInForeground']); //: false,
$this->setProperty('geoLocationAccess', $state['geoLocationAccess']); //             : true,
$this->setProperty('enableUrlOtherApps', $state['enableUrlOtherApps']); //           : true,
$this->setProperty('showNavigationBar', $state['showNavigationBar']); //             : false,
$this->setProperty('timeToScreenOffV2', $state['timeToScreenOffV2']); //             : "1200",
$this->setProperty('loadCurrentPageOnReload', $state['loadCurrentPageOnReload']); // : false,
$this->setProperty('lastVersionInfo', $state['lastVersionInfo']); //                 : "1.36.1",
$this->setProperty('loadOverview', $state['loadOverview']); //                       : false,
$this->setProperty('remoteAdminScreenshot', $state['remoteAdminScreenshot']); //     : true,
$this->setProperty('screenOnOnMotion', $state['screenOnOnMotion']); //               : true,
$this->setProperty('useWideViewport', $state['useWideViewport']); //                 : true,
$this->setProperty('enableTapSound', $state['enableTapSound']); //                   : true,
$this->setProperty('clientCaPassword', $state['clientCaPassword']); //               : "",

$this->setProperty('playMedia', $state['playMedia']); //
$this->setProperty('playMedia', $state['playMedia']); //
$this->setProperty('playMedia', $state['playMedia']); //
$this->setProperty('playMedia', $state['playMedia']); //
$this->setProperty('playMedia', $state['playMedia']); //
$this->setProperty('playMedia', $state['playMedia']); //
$this->setProperty('playMedia', $state['playMedia']); //
$this->setProperty('playMedia', $state['playMedia']); //
$this->setProperty('playMedia', $state['playMedia']); //
$this->setProperty('playMedia', $state['playMedia']); //
$this->setProperty('playMedia', $state['playMedia']); //
/*


forceScreenOrientation: "0",
movementDetection: false,
progressBarColor: -13611010,
formAutoComplete: true,
webHostFilter: false,
advancedKioskProtection: false,
swipeTabs: false,
screensaverPlaylist: "",
webcamAccess: true,
screenBrightness: "255",
urlWhitelist: "",
enableQrScan: true,
launcherInjectCode: "",
timeToRegainFocus: "0",
cloudService: false,
initialScale: "90",
kioskExitGesture: "2",
motionDetection: true,
resumeVideoAudio: true,
inUseWhileKeyboardVisible: false,
kioskPin: "",
remoteAdminCamshot: true,
bluetoothMode: "2",
reloadOnScreensaverStop: false,
forceSleepIfUnplugged: false,
actionBarInSettings: false,
timeToGoBackground: "0",
enablePopups: true,
actionBarQrScanButtonUrl: "",
screensaverOtherApp: false,
screensaverWallpaperURL: "fully://color#000000",
recreateTabsOnReload: false,
timeToClearSingleAppData: "0",
mdmDisableKeyguard: false,
knoxHideStatusBar: false,
addressBarBgColor: -2236963,
showAddressBar: false,
remoteAdminLan: true,
timeToShutdownOnPowerDisconnect: "0",
knoxDisableTaskManager: false,
knoxEnabled: false,
reloadPageFailure: "0",
cacheMode: "2",
knoxDisableEdgeScreen: false,
alarmSoundFileUrl: "",
folderCleanupTime: "",
disableOtherApps: false,
mdmDisableSafeModeBoot: false,
remoteAdminFileManagement: true,
knoxDisableMtp: false,
compassSensitivity: "50",
textSelection: true,
websiteIntegration: true,
motionFps: "5",
videoCaptureUploads: true,
reloadOnInternet: false,
enableLocalhost: true,
statusBarColor: 0,
usageStatistics: false,
isRunning: true,
fileUploads: true,
singleAppMode: false,
//---------------------------------------------------------------------------------------------------------
launcherApps: "[
  {
    "label": "Alarm Panel",
    "component": "com.thanksmister.iot.mqtt.alarmpanel\/com.thanksmister.iot.mqtt.alarmpanel.ui.activities.MainActivity"
  },
  {
    "label": "Chrome",
    "component": "com.android.chrome\/com.google.android.apps.chrome.Main"
  },
  {
    "label": "Files",
    "component": "com.google.android.apps.nbu.files\/com.google.android.apps.nbu.files.home.HomeActivity"
  },
  {
    "label": "FM-радио",
    "component": "com.android.fmradio\/com.android.fmradio.FmMainActivity"
  },
  {
    "label": "Fully Kiosk Browser",
    "component": "de.ozerov.fully\/de.ozerov.fully.MainActivity"
  },
  {
    "label": "ioBroker.PAW II",
    "component": "ru.codedevice.iobrokerpawii\/ru.codedevice.iobrokerpawii.SplashActivity"
  },
  {
    "label": "MajorDroid",
    "component": "ru.smartliving.majordroid\/ru.smartliving.majordroid.MainActivity"
  },
  {
    "label": "MQTT Clock",
    "component": "se.jplantin.jp.alarmclock\/se.jplantin.jp.alarmclock.ui.AlarmsActivity2"
  },
  {
    "label": "Tasker",
    "component": "net.dinglisch.android.taskerm\/net.dinglisch.android.taskerm.Tasker"
  },
  {
    "label": "YouTube",
    "component": "com.google.android.youtube\/com.google.android.youtube.app.honeycomb.Shell$HomeActivity"
  },
  {
    "label": "Браузер",
    "component": "com.yandex.browser\/com.yandex.browser.YandexBrowserActivity"
  },
  {
    "label": "Настройки",
    "component": "com.android.settings\/com.android.settings.Settings"
  },
  {
    "label": "MajorDoMo",
    "url": "http:\/\/192.168.10.26\/popup\/scenes\/1.html",
    "iconUrl": "http:\/\/192.168.10.26\/favicon.ico"
  }
]",
//---------------------------------------------------------------------------------------------
appLauncherBackgroundColor: -9145228,
reloadEachSeconds: "0",
forceImmersive: true,
mdmSystemAppsToEnable: "",
knoxDisableScreenCapture: false,
removeStatusBar: false,
knoxHideNavigationBar: false,
mdmDisableStatusBar: false,
folderCleanupList: "",
kioskWifiPin: "",
showShareButton: true,
knoxDisableMultiUser: false,
redirectBlocked: false,
forceSwipeUnlock: true,
jsAlerts: false,
screensaverDaydream: false,
mdmDisableUsbStorage: false,
screensaverFullscreen: true,
defaultWebviewBackgroundColor: -14079703,
batteryWarning: "35",
lockSafeMode: false,
scrollingDragging: true,
keepOnWhileFullscreen: true,
graphicsAccelerationMode: "2",
wifiKey: "Pavlik89217548469",
reloadOnScreenOn: false,
safeBrowsing: false,
deleteCookiesOnReload: false,
loadContentZipFileUrl: "",
sleepOnPowerDisconnect: false,
runInForeground: true,
screenOnOnMovement: false,
appLauncherScaling: "100",
motionSensitivity: "90",
knoxDisableHomeButton: false,
inactiveTabsBgColor: -4144960,
knoxDisableStatusBar: false,
accelerometerSensitivity: "80",
mqttBrokerUsername: "xbmc",
remoteFileMode: "1",
enableZoom: true,
playerCacheImages: true,
detectIBeacons: false,
navigationBarColor: 0,
mdmDisableAppsFromUnknownSources: false,
mdmMinimumPasswordLength: "5",
screensaverOtherAppIntent: "",
clientCaUrl: "",
deleteCacheOnReload: true,
stopScreensaverOnMovement: false,
knoxDisableOtaUpgrades: false,
fontSize: "100",
motionDetectionAcoustic: false,
stopScreensaverOnMotion: true,
audioRecordUploads: true,
timeToClearLauncherAppData: "0",
showAppLauncherOnStart: false,
mdmAppLockTaskWhitelist: "",
knoxDisableSafeMode: false,
showRefreshButton: true,
knoxDisableVolumeButtons: false,
autoImportSettings: true,
showForwardButton: true,
appToRunOnStart: "",
mqttEnabled: true,
motionSensitivityAcoustic: "90",
killAppsBeforeStartingList: "",
keepSleepingIfUnplugged: false,
userAgent: "0",
injectJsCode: "",
disableVolumeButtons: false,
showNewTabButton: false,
errorURL: "file:///sdcard/paw_2/www/index.php",
authUsername: "",
showBackButton: true,
enableBackButton: true,
ignoreSSLerrors: true,
webviewDebugging: true,
disableStatusBar: false,
confirmExit: false,
showProgressBar: true,
knoxDisableRecentTaskButton: false,
remotePdfFileMode: "0",
singleAppIntent: "",
urlBlacklist: "",
remoteAdminPassword: "197994",
setWifiWakelock: false,
customUserAgent: "",
screenOffInDarkness: false,
ignoreJustOnceLauncher: true,
actionBarCustomButtonUrl: "fully://launcher",
mdmSystemUpdatePolicy: "0",
enablePullToRefresh: false,
touchInteraction: true,
enableFullscreenVideos: true,
localPdfFileMode: "0",
showTabCloseButtons: false,
showMenuHint: false,
disableHomeButton: false,
appLauncherTextColor: -1184275,
touchesOtherAppsBreakIdle: false,
movementBeaconList: "",
mdmRuntimePermissionPolicy: "0",
fadeInOutDuration: "200",
thirdPartyCookies: false,
showPrintButton: true,
keepScreenOn: true,
knoxDisableMultiWindowMode: false,
volumeLicenseKey: "",
actionBarBgColor: -15906911,
disableCamera: false,
showCamPreview: false,
addXffHeader: true,
tabsFgColor: -16777216,
remoteAdmin: true,
forceScreenUnlock: true,
mdmAppsToDisable: "",
enableVersionInfo: false,
knoxDisableAirCommandMode: false,
reloadOnWifiOn: false,
sleepSchedule: "",
rebootTime: "",
actionBarTitle: "Fully Kiosk Browser",
knoxDisableBackButton: false,
actionBarIconUrl: "",
timeToScreensaverV2: "0",
kioskWifiPinCustomIntent: "",
playAlarmSoundOnMovement: false,
addRefererHeader: true,
startURL: "http://192.168.10.26/popup/scenes/1.html",
remoteAdminSingleAppExit: false,
movementBeaconDistance: "5",
disablePowerButton: false,
showTabs: false,
microphoneAccess: true,
value: "5",
pageTransitions: false,
restartAfterUpdate: true,
swipeNavigation: false,
skipReloadIfStartUrlShowing: false,
setRemoveSystemUI: false,
ignoreMotionWhenMoving: false,
searchProviderUrl: "https://www.google.com/search?q=",
setCpuWakelock: true,
playAlarmSoundUntilPin: false,
knoxDisableCamera: false,
desktopMode: false,
cameraCaptureUploads: true,
autoplayAudio: true,
autoplayVideos: true,
darknessLevel: "10",
preventSleepWhileScreenOff: true,
mdmLockTask: false,
knoxDisablePowerButton: false,
readNfcTag: false
*/